I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 327, in script
    $ current_objectives['Sign Eva up for Ballroom'] = "In Progress"
  File "game/script.rpy", line 327, in <module>
    $ current_objectives['Sign Eva up for Ballroom'] = "In Progress"
NameError: name 'current_objectives' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 327, in script
    $ current_objectives['Sign Eva up for Ballroom'] = "In Progress"
  File "/Users/shengjieji/Desktop/renpy-8.1.3-sdk/renpy/ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/shengjieji/Desktop/renpy-8.1.3-sdk/renpy/python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 327, in <module>
    $ current_objectives['Sign Eva up for Ballroom'] = "In Progress"
NameError: name 'current_objectives' is not defined

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.1.3.23091805
Chinese Detective 1.0
Sun Sep  8 22:45:13 2024
